# Generated by Django 3.2.9 on 2022-12-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
